apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: mongo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/proshop-mongo-data
